GET http://localhost:3000/api/giderler

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "email" : "furkanakt3411@gmail.com",
    "sifre" : "1231231"
}

###

POST http://localhost:3000/api/users/giris
Content-Type: application/json

{
    "email" : "furkanakt@gmail.com",
    "sifre" : "1231231"
}

###

DELETE http://localhost:3000/api/giderler/63a5dc23ea81e108f22767fe
Content-Type: application/json